name: test
channels:
  - conda-forge
dependencies:
  - numpy>=1.7
  - scipy>=1.0.0
  - scikit-learn>=0.22
  - pymatsolver>=0.1.1
  - matplotlib
  - properties>=0.5.2
  - vectormath>=0.2.0
  - discretize>=0.7.1
  - geoana>=0.3.0
  - empymod
  - pandas
  - dask
  - zarr
  - fsspec
  - jupyter
  - h5py
  - sphinx
  - sphinx-gallery>=0.1.13
  - sphinx-toolbox
  - sphinxcontrib-apidoc
  - pydata-sphinx-theme
  - nbsphinx
  - numpydoc
  - pillow
  - pylint
  - sympy
  - wheel
  - pytest
  - pytest-cov
  - toolz
  - twine
  - memory_profiler
  - plotly
  - pyvista
  - pip
  - python=3.7
